configuration/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from studyplanner.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls), 
    url(r'^$', home, name='home'),
    url(r'^planner/', include('studyplanner.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

studyplanner/urls.py
from django.conf.urls import url
from . import views

app_name = 'studyplanner'

urlpatterns = [
	url(r'^my-plans/$', views.my_plans, name='my-plans'),

	url(r'^archived-plans/$',views.archived_plans, name='archived-plans'),


	url(r'^create-plan/$', views.create_plan, name='create-plan'),

	url(r'^edit-plan/(?P<pk>\d+)/$',views.edit_plan, name='edit-plan'),

	url(r'^plan-detail/(?P<pk>\d+)/$', views.plan_detail, name='plan-detail'),

	url(r'^archive-plan/(?P<pk>\d+)/$',views.archive_plan, name='archive-plan'),

	url(r'^unarchive-plan/(?P<pk>\d+)/$',views.unarchive_plan, name='unarchive-plan'),

	url(r'^complete-plan/(?P<pk>\d+)/$',views.complete_plan, name='complete-plan'),

	url(r'^print-plan/(?P<pk>\d+)/$',views.print_plan, name='print-plan'),


	url(r'^add-subject/(?P<pk>\d+)/$',views.add_subject, name='add-subject'),

	url(r'^edit-subject/(?P<pk>\d+)/$',views.edit_subject, name='edit-subject'),

	url(r'^complete-subject/(?P<pk>\d+)/$',views.complete_subject, name='complete-subject'),

	url(r'^delete-subject/(?P<pk>\d+)/$',views.DeleteSubject.as_view(), name='delete-subject'),


	url(r'^add-subtopic/(?P<pk>\d+)/$',views.add_subtopic, name='add-subtopic'),

	url(r'^edit-subtopic/(?P<pk>\d+)/$',views.edit_subtopic, name='edit-subtopic'),

	url(r'^complete-subtopic/(?P<pk>\d+)/$',views.complete_subtopic, name='complete-subtopic'),

	url(r'^delete-subtopic/(?P<pk>\d+)/$',views.DeleteSubtopic.as_view(), name='delete-subtopic'),


	url(r'^add-path/(?P<pk>\d+)/$',views.add_path, name='add-path'),

	url(r'^edit-path/(?P<pk>\d+)/$',views.edit_path, name='edit-path'),

	url(r'^complete-path/(?P<pk>\d+)/$',views.complete_path, name='complete-path'),

	url(r'^delete-path/(?P<pk>\d+)/$',views.DeletePath.as_view(), name='delete-path'),


	url(r'^add-method/(?P<pk>\d+)/(?P<pathpk>\d+)/(?P<flag>[\w-]+)/$',views.add_method, name='add-method'),

	url(r'^edit-method/(?P<pk>\d+)/$',views.edit_method, name='edit-method'),

	url(r'^complete-method/(?P<pk>\d+)/(?P<flag>[\w-]+)/$',views.complete_method, name='complete-method'),

	url(r'^delete-method/(?P<pk>\d+)/$',views.DeleteMethod.as_view(), name='delete-method'),			
]

studyplanner/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Plan(models.Model):
	name = models.CharField(max_length=100,null=False,blank=False)
	is_completed = models.BooleanField(default=False)
	description = models.TextField(default='')
	deadline = models.DateField(default=datetime.date.today)
	completed_subjects = models.IntegerField(default=0)
	completed_paths = models.IntegerField(default=0)
	completed_on = models.DateField(default=datetime.date.today)
	archived = models.BooleanField(default=False)

	class Meta:
		ordering = ['is_completed']

	def __str__(self):
		return self.name

class Subject(models.Model):
	name = models.CharField(max_length=500,null=False,blank=False)
	plan = models.ForeignKey(Plan, on_delete=models.CASCADE, null=False)
	description = models.TextField(default='')
	is_completed = models.BooleanField(default=False)
	deadline = models.DateField(default=datetime.date.today)
	completed_subtopics = models.IntegerField(default=0)
	completed_methods = models.IntegerField(default=0)
	completed_on = models.DateField(default=datetime.date.today)

	class Meta:
		ordering = ['is_completed','deadline']

	def __str__(self):
		return self.name

class Path(models.Model):
	name = models.CharField(max_length=500,null=False,blank=False)
	plan = models.ForeignKey(Plan, on_delete=models.CASCADE, null=True)
	description = models.TextField(default='')
	is_completed = models.BooleanField(default=False)
	deadline = models.DateField(default=datetime.date.today)
	completed_methods = models.IntegerField(default=0)
	completed_on = models.DateField(default=datetime.date.today)

	class Meta:
		ordering = ['is_completed']

	def __str__(self):
		return self.name

class Subtopic(models.Model):
	name = models.CharField(max_length=500,null=False,blank=False)
	subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=False)
	description = models.TextField(default='')
	is_completed = models.BooleanField(default=False)
	deadline = models.DateField(default=datetime.date.today)
	completed_methods = models.IntegerField(default=0)
	completed_on = models.DateField(default=datetime.date.today)

	class Meta:
		ordering = ['is_completed','deadline']

	def __str__(self):
		return self.name

class Method(models.Model):
	name = models.CharField(max_length=100,null=False,blank=False)
	path = models.ForeignKey(Path, on_delete=models.CASCADE,null=True)
	subject = models.ForeignKey(Subject, on_delete=models.CASCADE,null=True,blank=True)
	subtopic = models.ForeignKey(Subtopic, on_delete=models.CASCADE,null=True,blank=True)
	description = models.TextField(default='')
	is_completed = models.BooleanField(default=False)
	deadline = models.DateField(default=datetime.date.today)
	completed_on = models.DateField(default=datetime.date.today)

	class Meta:
		ordering = ['is_completed','deadline']

	def __str__(self):
		return self.name

studyplanner/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import datetime
import json
from .models import Plan,Path,Subject,Subtopic,Method
from .forms import PlanForm, SubjectForm, SubtopicForm, PathForm, MethodForm, EditPlanForm, EditSubjectForm, EditSubtopicForm, EditPathForm, EditMethodForm

# Create your views here.

def home(request):
	plans = Plan.objects.filter(is_completed=False,archived=False)
	return render(request, 'studyplanner/index.html', {'plans':plans})

def my_plans(request):
	plans = Plan.objects.filter(archived=False)
	return render(request, 'studyplanner/my_plans.html', {'plans':plans})

def archived_plans(request):
	plans = Plan.objects.filter(archived=True)
	return render(request, 'studyplanner/archived_plans.html', {'plans':plans})

def create_plan(request):
	if request.method == 'POST':
		form = PlanForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			if cd['deadline'] < datetime.date.today():
				messages.error(request, "Invalid deadline. Please fill a correct deadline.")
				return redirect('studyplanner:create-plan')
			else:
				new_plan = Plan.objects.create(name=cd['name'])
				new_plan.deadline = cd['deadline']
				new_plan.description = cd['description']
				new_plan.save()
				messages.success(request, "Study Plan successfully added. You can add subjects and paths now.")
				return redirect('studyplanner:plan-detail', pk=new_plan.pk)
	else:
		form = PlanForm()
	return render(request, 'studyplanner/forms/create_plan.html', {'form':form})

def edit_plan(request,pk):
	plan = get_object_or_404(Plan, pk=pk)
	title = plan.name
	if not plan.is_completed:
		if request.method == 'POST':
			form = EditPlanForm(request.POST,instance=plan)
			if form.is_valid():
				cd = form.cleaned_data
				if cd['deadline'] < datetime.date.today():
					messages.error(request, "Invalid deadline. Please fill a correct deadline.")
					return redirect('studyplanner:edit-plan', pk=pk)
				else:
					plan.name = cd['name']
					plan.deadline = cd['deadline']
					plan.description = cd['description']
					plan.save()
					messages.success(request, "Study Plan updated successfully.")
					return redirect('studyplanner:plan-detail', pk=pk)
		else:
			form = EditPlanForm(instance=plan)
		return render(request, 'studyplanner/forms/edit_form.html', {'form':form,'title':title})
	else:
		messages.info(request, "Plan is already completed. Cannot edit it further.")
	return redirect('studyplanner:plan-detail',pk=plan.pk)

def plan_detail(request,pk):
	plan = get_object_or_404(Plan, pk=pk)
	paths = Path.objects.filter(plan=plan)
	if plan.archived:
		messages.error(request, "Plan doesn't exist")
		return redirect('home')
	subject_form = SubjectForm()
	subtopic_form = SubtopicForm()
	path_form = PathForm()
	method_form = MethodForm()
	return render(request, 'studyplanner/plan_detail.html', {'plan':plan,'paths':paths,'subject_form':subject_form,'subtopic_form':subtopic_form,'path_form':path_form,'method_form':method_form})

def archive_plan(request,pk):
	plan = get_object_or_404(Plan, pk=pk)
	if plan.archived:
		messages.info(request, "Plan already archived")
	else:
		plan.archived = True
		plan.save()
		messages.success(request, "Plan archived")
	return redirect('home')

def unarchive_plan(request,pk):
	plan = get_object_or_404(Plan, pk=pk)
	if not plan.archived:
		messages.info(request, "Plan already unarchived")
	else:
		plan.archived = False
		plan.save()
		messages.success(request, "Plan unarchived")
	return redirect('home')

def complete_plan(request,pk):
	plan = get_object_or_404(Plan, pk=pk)
	if not plan.is_completed:
		plan.is_completed = True
		plan.completed_on = datetime.date.today()
		plan.save()
		messages.success(request, "{} Completed Successfully".format(plan))
	else:
		messages.error(request, "{} Alread Completed on {}".format(plan,plan.completed_on))
	return redirect('studyplanner:plan-detail',pk=plan.pk)

def print_plan(request,pk):
	plan = get_object_or_404(Plan,pk=pk)
	paths = Path.objects.filter(plan=plan)
	if plan.archived:
		messages.error(request, "Plan doesn't exist")
		return redirect('home')
	subject_form = SubjectForm()
	subtopic_form = SubtopicForm()
	path_form = PathForm()
	method_form = MethodForm()
	return render(request, 'studyplanner/print_plan.html', {'plan':plan,'paths':paths,'subject_form':subject_form,'subtopic_form':subtopic_form,'path_form':path_form,'method_form':method_form})

def add_subject(request,pk):
	plan = get_object_or_404(Plan, pk=pk)
	if not plan.archived:
		if not plan.is_completed:
			if request.method == 'POST':
				if request.is_ajax():
					dt = request.POST.get('deadline')
					dt=dt.split(" ")
					deadline = datetime.date(int(dt[0]),int(dt[1]),int(dt[2]))
					if (deadline < datetime.date.today()) and (deadline <= plan.deadline):
						messages.error(request, "Invalid deadline. Please fill a correct deadline.")
					else:
						new_subject = Subject.objects.create(name=request.POST.get('name'),plan=plan)
						new_subject.description = request.POST.get('description')
						new_subject.deadline = deadline
						new_subject.save()
						messages.success(request, "{} added successfully".format(request.POST.get('name')))
		else:
			messages.error(request, "Plan is already completed on {}".format(plan.completed_on))
	else:
		messages.error(request, "Plan doesn't exist")
	return JsonResponse({
		'success':True
	})

def edit_subject(request,pk):
	subject = get_object_or_404(Subject, pk=pk)
	title = subject.name
	if not subject.plan.archived:
		if (not subject.plan.is_completed) or (not subject.is_completed):
			if request.method == 'POST':
				form = EditSubjectForm(request.POST,instance=subject)
				if form.is_valid():
					cd = form.cleaned_data
					if (cd['deadline'] < datetime.date.today()) and (cd['deadline'] < subject.plan.deadline):
						messages.error(request, "Invalid deadline. Please fill a correct deadline.")
						return redirect('studyplanner:edit-subject', pk=pk)
					else:
						subject.name = cd['name']
						subject.description = cd['description']
						subject.deadline = cd['deadline']
						subject.save()
						messages.success(request, "{} updated successfully".format(cd['name']))
						return redirect('studyplanner:plan-detail', pk=subject.plan.pk)
			else:
				form = EditSubjectForm(instance=subject)
			return render(request, 'studyplanner/forms/edit_form.html', {'form':form,'title':title})
		else:
			messages.error(request, "Subject/Plan is already completed.")
	else:
		messages.error(request, "Plan/Subject doesn't exist")
	return redirect('home')

def complete_subject(request,pk):
	subject = get_object_or_404(Subject,pk=pk)
	if not subject.plan.archived:
		if subject.is_completed:
			messages.info(request, "{} already completed on {}".format(subject,subject.completed_on))
		else:
			subject.is_completed = True
			subject.completed_on = datetime.date.today()
			plan = subject.plan
			plan.completed_subjects += 1
			plan.save()
			subject.save()
			messages.success(request, "{} Completed Successfully".format(subject))
		return redirect('studyplanner:plan-detail',pk=subject.plan.pk)
	else:
		messages.error(request,"Plan is archived")
	return redirect('home')

def add_subtopic(request,pk):
	subject = get_object_or_404(Subject, pk=pk)
	if not subject.plan.archived:
		if not subject.is_completed:
			if request.method == 'POST':
				if request.is_ajax():
					dt = request.POST.get('deadline')
					dt=dt.split(" ")
					deadline = datetime.date(int(dt[0]),int(dt[1]),int(dt[2]))
					if (deadline < datetime.date.today()) and (deadline <= subject.deadline):
						messages.error(request, "Invalid deadline. Please fill a correct deadline.")
					else:
						new_subtopic = Subtopic.objects.create(name=request.POST.get('name'),subject=subject)
						new_subtopic.description = request.POST.get('description')
						new_subtopic.deadline = deadline
						new_subtopic.save()
						messages.success(request, "{} added successfully".format(request.POST.get('name')))
		else:
			messages.error(request, "Subject is already completed on {}".format(subject.completed_on))
	else:
		messages.error(request, "Plan doesn't exist")
	return JsonResponse({
		'success':True
	})

def edit_subtopic(request,pk):
	subtopic = get_object_or_404(Subtopic, pk=pk)
	title = subtopic.name
	if not subtopic.subject.plan.archived:
		if not subtopic.is_completed:
			if request.method == 'POST':
				form = EditSubtopicForm(request.POST,instance=subtopic)
				if form.is_valid():
					cd = form.cleaned_data
					if (cd['deadline'] < datetime.date.today()) and (cd['deadline'] < subtopic.subject.deadline):
						messages.error(request, "Invalid deadline. Please fill a correct deadline.")
						return redirect('studyplanner:edit-subtopic', pk=pk)
					else:
						subtopic.name = cd['name']
						subtopic.description = cd['description']
						subtopic.deadline = cd['deadline']
						subtopic.save()
						messages.success(request, "{} updated successfully".format(cd['name']))
						return redirect('studyplanner:plan-detail', pk=subtopic.subject.plan.pk)
			else:
				form = EditSubtopicForm(instance=subtopic)
			return render(request, 'studyplanner/forms/edit_form.html', {'form':form,'title':title})
		else:
			messages.error(request, "Subtopic is already completed. Cannot edit it further.")
	else:
		messages.error(request, "Plan/Subtopic doesn't exist")
	return redirect('home')

def complete_subtopic(request,pk):
	subtopic = get_object_or_404(Subtopic,pk=pk)
	if not subtopic.subject.plan.archived:
		if subtopic.is_completed:
			messages.info(request, "{} already completed on {}".format(subtopic,subtopic.completed_on))
		else:
			subtopic.is_completed = True

studyplanner/templates/studyplanner/archived_plans.html
{% extends 'studyplanner/base.html' %}

{% block title %}StudyPlanner{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="pageBody">
		<div class="row">
			<div class="col-sm-offset-2 col-md-offset-2 col-sm-8 col-md-8">
				<div class="text-center" style="padding-top:35pt; padding-bottom: 35pt;">
					<b class="extraBig">Archived Plans</b>
					<hr>
				</div>
			</div>
		</div>
		<div class="panels">
			{% if plans.count > 0 %}
				{% include 'studyplanner/messages.html' %}
				<div class="row">
					<div class="table-responsive dataTable">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Plan no.</th>
									<th>Name</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								{% for plan in plans %}
									<tr>
										<td>{{ forloop.counter }}</td>
										<td>{{ plan.name }}</td>
										<td>
											<a href="{% url 'studyplanner:unarchive-plan' pk=plan.pk %}">
												<button class="btn btn-success"><span class="glyphicon glyphicon-upload"></span>&nbsp; Unarchive</button>
											</a>
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			{% else %}
				<div class="text-center">
					<h3>No Archived Plans!</h3>
				</div>
			{% endif %}
		</div>
	</div>
</div>

{% endblock %}

studyplanner/templates/studyplanner/plan_detail.html
{% extends 'studyplanner/base.html' %}

{% block title %}{{ plan.name }}{% endblock %}

{% block content %}
	<div id="add_modal" class="modal">
		{% include 'studyplanner/modal_template.html' %}
	</div>
	<div class="container-fluid">
		<div class="panels">
			<h2 class="text-center pageTitle">
				{{ plan.name }}
			{% if not plan.is_completed %}
				<a href="{% url 'studyplanner:edit-plan' pk=plan.pk %}" title="Edit Plan details">
					<button class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span></button>
				</a>	
			{% endif %}			
			</h2>
			{% if not plan.is_completed %}
				<h5 class="text-center pageTitle" style="color: red;">Deadline: {{ plan.deadline }}</h5>
			{% else %}
				<h5 class="text-center pageTitle" style="color: green;">Completed</h5>
			{% endif %}
			<div class="text-center">
				<a href="{% url 'studyplanner:print-plan' pk=plan.pk %}">
					<button class="btn btn-info"><span class="glyphicon glyphicon-eye-open"></span>&nbsp;<span class="glyphicon glyphicon-print"></span>&nbsp; View/Print</button>
				</a>
			{% if not plan.is_completed %}
				<a href="{% url 'studyplanner:complete-plan' pk=plan.pk %}">
					<button class="btn btn-default completePlan"><span class="glyphicon glyphicon-ok"></span>&nbsp; Mark as Complete</button>
				</a>
			{% else %}
				<button class="btn btn-default completedPlan"><span class="glyphicon glyphicon-ok"></span>&nbsp; Completed</button>
			{% endif %}
				<a href="{% url 'studyplanner:archive-plan' pk=plan.pk %}">
					<button class="btn btn-danger"><span class="glyphicon glyphicon-download"></span>&nbsp; Archive Plan</button>
				</a>
			</div>
			{% include 'studyplanner/messages.html' %}
			<div class="row">
				<div class="table-responsive dataTable">	
					<table class="table">
						<thead>
							<tr>
								<td></td>
								<th>Subjects</th>
									{% for path in paths %}
										<th>
											<span class="pathName" title="{{ path.description }}">{{ path.name }}</span>
										{% if not plan.is_completed %}
											<a href="{% url 'studyplanner:edit-path' pk=path.pk %}"><span class="glyphicon glyphicon-pencil itemEditBtn" title="Edit Path details"></span></a>
										{% endif %}
											<br>
											{% if path.is_completed %}
												<span class="text-success contentfooter"><span class="glyphicon glyphicon-ok-sign"></span>&nbsp;Completed</span>
											{% else %}											
												<span class="text-danger contentfooter">
													<span class="glyphicon glyphicon-calendar"></span>{{path.deadline }}
													&nbsp; 
												{% if not plan.is_completed %}
													<span class="glyphicon glyphicon-trash removeItemBtn" title="Remove Item" onclick="openActionModal('path','remove','{{ path.name }}','{{ path.pk }}')"></span>
												{% endif %}
												</span>												
												</span>								
											{% endif %}
										</th>
									{% endfor %}
							{% if not plan.is_completed %}
								<th>
									<button onclick="openFormModal('path','{{ plan.pk }}')" class="btn btn-success">
										<span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add Path
									</button>
								</th>
							{% endif %}
							</tr>
						</thead>
						<tbody>
							{% for subject in plan.subject_set.all %}
								<tr>
									<td>
										<span>{{ forloop.counter }}.</span>
									</td>
									<th>
										<span>
											<h4 class="pageTitle"><b>
												<span class="subjectName" title="{{ subject.description }}">{{ subject.name }}</span>
											{% if not subject.is_completed and not plan.is_completed %}
												<a href="{% url 'studyplanner:edit-subject' pk=subject.pk %}"><span class="glyphicon glyphicon-pencil itemEditBtn" title="Edit Subject details"></span></a>
											{% endif %}
											</b></h4>
											{% if subject.is_completed %}
												<span class="text-success contentfooter"><span class="glyphicon glyphicon-ok-sign"></span>&nbsp;Completed</span>
											{% else %}
												<span class="text-danger contentfooter">
													<span class="glyphicon glyphicon-exclamation-sign"></span>&nbsp;Not completed
													&nbsp; 
													<span class="glyphicon glyphicon-calendar"></span>&nbsp;{{ subject.deadline }}
												{% if not plan.is_completed %}
													&nbsp;<span class="glyphicon glyphicon-trash removeItemBtn" title="Remove Item" onclick="openActionModal('subject','remove','{{ subject.name }}','{{ subject.pk }}')"></span>
												{% endif %}
												</span>
												{% if not plan.is_completed %}
												<span class="itemComplete">
													<br><button class="btn btn-sm btn-default" onclick="openActionModal('subject','markComplete','{{ subject.name }}','{{ subject.pk }}')">Mark as complete&nbsp; <span class="glyphicon glyphicon-ok"></span></button>
												</span>
												{% endif %}
											{% endif %}
										</span>
									</th>
								{% for path in paths %}
									<th>
										{% for method in subject.method_set.all %}
											{% if method.path == path %}
												<span class="text-{% if method.is_completed %}success{% else %}info{%endif%} text-xs">
													<span class="methodName" title="{{method.description}}">{{ method.name }}</span>
													{% if not method.is_completed and not subject.is_completed and not plan.is_completed %}
														<span class="glyphicon glyphicon-minus-sign removeItemBtn" title="Remove Item" onclick="openActionModal('subjectMethod','remove','{{ method.name }}','{{ method.pk }}')"></span>
														<a href="{% url 'studyplanner:edit-method' pk=method.pk %}"><span class="glyphicon glyphicon-pencil itemEditBtn" title="Edit Method details"></span></a>
														<span class="glyphicon glyphicon-ok-sign methodCompleteBtn" title="Mark as completed" onclick="openActionModal('subjectMethod','markComplete','{{ method.name }}','{{ method.pk }}','sb')"></span>
													{% else %}
														{% if method.is_completed %}
														<span class="glyphicon glyphicon-ok-sign"></span>
														{% endif %}
													{% endif %}
												</span>
												<br>
											{% endif %}	
										{% endfor %}
										{% if not subject.is_completed and not plan.is_completed %}
											<button onclick="openFormModal('subjectMethod','{{ subject.pk }}','{{ path.pk }}','sb')" class="btn btn-info btn-xs">
												<span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add Method
											</button>
										{% endif %}
									</th>
								{% endfor %}
								</tr>
								{% for subtopic in subject.subtopic_set.all %}
									<tr>
										<td></td>
										<td>
											<h5 class="pageTitle"><i>
												<b class="subtopicName" title="{{ subtopic.description }}">{{ subtopic.name }}</b>
												{% if not subtopic.is_completed and not subtopic.subject.is_completed and not plan.is_completed %}
													<a href="{% url 'studyplanner:edit-subtopic' pk=subtopic.pk %}"><span class="glyphicon glyphicon-pencil itemEditBtn" title="Edit Subtopic details"></span></a>
												{% endif %}
											</i></h5>
											{% if subtopic.is_completed %}
												<span class="text-success contentfooter"><span class="glyphicon glyphicon-ok-sign"></span>&nbsp;Completed</span>
											{% else %}
												<span class="text-danger contentfooter">
												<b>
													<span class="glyphicon glyphicon-exclamation-sign"></span>&nbsp;Not completed
													&nbsp; <span class="glyphicon glyphicon-calendar"></span>&nbsp;{{ subtopic.deadline }}
												{% if not subtopic.subject.is_completed and not plan.is_completed  %}
													&nbsp;<span class="glyphicon glyphicon-trash removeItemBtn" title="Remove Item" onclick="openActionModal('subtopic','remove','{{ subtopic.name }}','{{ subtopic.pk }}')"></span>
												{% endif %}
												</b>
												</span>
												{% if not subtopic.subject.is_completed and not plan.is_completed  %}
													<span class="itemComplete">
														<br><button class="btn btn-sm btn-default" onclick="openActionModal('subtopic','markComplete','{{ subtopic.name }}','{{ subtopic.pk }}')">Mark as complete&nbsp; <span class="glyphicon glyphicon-ok"></span></button>
													</span>
												{% endif %}
											{% endif %}
										</td>
									{% for path in paths %}
										<td>
											{% for method in subtopic.method_set.all %}
												{% if method.path == path %}
													<span class="text-{% if method.is_completed %}success{% else %}info{%endif%} text-xs">
														<span class="methodName" title="{{method.description}}">{{ method.name }}</span>
														{% if not method.is_completed and not subtopic.subject.is_completed and not subtopic.is_completed and not plan.is_completed  %}
															<span class="glyphicon glyphicon-minus-sign removeItemBtn" title="Remove Item" onclick="openActionModal('subtopicMethod','remove','{{ method.name }}','{{ method.pk }}')"></span>
															<a href="{% url 'studyplanner:edit-method' pk=method.pk %}"><span class="glyphicon glyphicon-pencil itemEditBtn" title="Edit Method details"></span></a>
															<span class="glyphicon glyphicon-ok-sign methodCompleteBtn" title="Mark as completed" onclick="openActionModal('subtopicMethod','markComplete','{{ method.name }}','{{ method.pk }}','st')"></span>
														{% else %}
															{% if method.is_completed %}
															<span class="glyphicon glyphicon-ok-sign"></span>
															{% endif %}
														{% endif %}
													</span>
													<br>
												{% endif %}
											{% endfor %}
											{% if not subtopic.is_completed and not subtopic.subject.is_completed and not plan.is_completed  %}
												<button onclick="openFormModal('subtopicMethod','{{ subtopic.pk }}','{{ path.pk }}','st')" class="btn btn-info btn-xs">
													<span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add Method
												</button>
											{% endif %}
										</td>
									{% endfor %}
									</tr>
								{% endfor %}
							{% if not subject.is_completed and not plan.is_completed %}
								<tr>
									<td></td>
									<td>
										<button onclick="openFormModal('subtopic','{{ subject.pk }}')" class="btn btn-default btn-xs">
											<span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add Subtopic
										</button>
									</td>
								</tr>
							{% endif %}
							{% endfor %}
						{% if not plan.is_completed %}
							<tr>
								<td></td>
								<td>
									<button onclick="openFormModal('subject','{{ plan.pk }}')" class="btn btn-success">
										<span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add Subject
									</button>
								</td>
							</tr>
						{% endif %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
{% endblock %}